# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "michelada/Kali"
  config.ssh.username = 'vagrant'
  config.ssh.private_key_path = "./id_rsa_insecure"
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.box_version = "0.0.2"
  config.vm.network "private_network", ip: "192.168.33.2",
    auto_config: false
end
